### ISSUE TITLE
LinAlgError: failed to factorize or solve matrix

### ISSUE THREAD

**Issue by eas342** [exoplanet-dev/celerite2#25]
celerite2 version: 0.1.1.dev4+gcee9a0f
theano: 1.0.11
python: 3.6.7

### Description
I keep running into a LinAlgError that I can't figure out. I was expecting to be able to sample a Gaussian process based on the `exoplanet` example (https://gallery.exoplanet.codes/en/latest/tutorials/quick-tess/) and modified it a little bit, but couldn't get it to run with a Matern nor SHOTerm kernel.

### What I did
Here's the most minimal working example I could make.

``` python
import pymc3 as pm
import numpy as np
from celerite2.theano import terms, GaussianProcess

x_JD = np.array([2458899.75295227, 2458899.75992418, 2458899.76689609,
                 2458899.773868  , 2458899.78083991, 2458899.78781182,
                 2458899.79478373, 2458899.80175564, 2458899.80872755,
                 2458899.81569946, 2458899.82267136, 2458899.82964327,
                 2458899.83661518, 2458899.84358709, 2458899.850559  ,
                 2458899.85753091, 2458899.86450282])
x = x_JD - np.median(x_JD)
y = np.array([ 999.91776623,  999.70908473,  999.41758557, 1000.42187202,
              1000.33801407,  999.57517094,  999.72223547, 1000.19105569,
              1000.27274928, 1000.78978838, 1000.08780841, 1000.29321361,
              1000.17255564, 1000.40390643,  999.97807388, 1000.60678241,
               999.35199641])

with pm.Model() as model:
    
    resid = y
    
    sigma_lc = pm.Lognormal("sigma_lc", mu=-1, sigma=3)
    rho_gp = pm.Lognormal("rho_gp", mu=0, sd=10)
    sigma_gp = pm.Lognormal("sigma_gp", mu=-1, sigma=3)
    
    kernel = terms.Matern32Term(sigma=sigma_gp,rho=rho_gp)
    
    gp = GaussianProcess(kernel, t=x, yerr=sigma_lc)
    gp.marginal("gp", observed=resid)
    pm.Deterministic("gp_pred", gp.predict(resid))
        
    trace = pm.sample(tune=3000, 
                      draws=3000, 
                      start=model.test_point, 
                      cores=2, 
                      chains=2, 
                      init="adapt_full", 
                      target_accept=0.9)
```

<details>
  <summary>Click for the full traceback</summary>
  
```
/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py:468: FutureWarning: In an upcoming release, pm.sample will return an `arviz.InferenceData` object instead of a `MultiTrace` by default. You can pass return_inferencedata=True or return_inferencedata=False to be safe and silence this warning.
  FutureWarning,
Auto-assigning NUTS sampler...
Initializing NUTS using adapt_full...
/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/quadpotential.py:514: UserWarning: QuadPotentialFullAdapt is an experimental feature
  warnings.warn("QuadPotentialFullAdapt is an experimental feature")
Multiprocess sampling (2 chains in 2 jobs)
NUTS: [sigma_gp, rho_gp, sigma_lc]
 1.22% [146/12000 00:03<04:47 Sampling 2 chains, 0 divergences]
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/gof/op.py", line 913, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 120, in perform
    func(*args)
celerite2.backprop.LinAlgError: failed to factorize or solve matrix

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/parallel_sampling.py", line 138, in run
    self._start_loop()
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/parallel_sampling.py", line 192, in _start_loop
    point, stats = self._compute_point()
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/parallel_sampling.py", line 217, in _compute_point
    point, stats = self._step_method.step(self._point)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/arraystep.py", line 273, in step
    apoint, stats = self.astep(array)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/base_hmc.py", line 169, in astep
    hmc_step = self._hamiltonian_step(start, p0, step_size)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 185, in _hamiltonian_step
    divergence_info, turning = tree.extend(direction)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 276, in extend
    self.right, self.depth, floatX(np.asarray(self.step_size))
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 369, in _build_subtree
    tree2, diverging, turning = self._build_subtree(tree1.right, depth - 1, epsilon)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 369, in _build_subtree
    tree2, diverging, turning = self._build_subtree(tree1.right, depth - 1, epsilon)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 365, in _build_subtree
    tree1, diverging, turning = self._build_subtree(left, depth - 1, epsilon)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 363, in _build_subtree
    return self._single_step(left, epsilon)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/nuts.py", line 325, in _single_step
    right = self.integrator.step(epsilon, left)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/integration.py", line 69, in step
    return self._step(epsilon, state)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/step_methods/hmc/integration.py", line 102, in _step
    logp = self._logp_dlogp_func(q_new, q_new_grad)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/model.py", line 733, in __call__
    output = self._theano_function(array)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/compile/function/types.py", line 989, in __call__
    storage_map=getattr(self.fn, "storage_map", None),
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/gof/link.py", line 343, in raise_with_op
    raise exc_value.with_traceback(exc_trace)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/compile/function/types.py", line 974, in __call__
    if output_subset is None
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/gof/op.py", line 913, in rval
    r = p(n, [x[0] for x in i], o)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 120, in perform
    func(*args)
celerite2.backprop.LinAlgError: failed to factorize or solve matrix
Apply node that caused the error: _CeleriteOp{name='factor_fwd', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]})
Toposort index: 34
Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(17,), (2,), (17,), (17, 2), (17, 2)]
Inputs strides: [(8,), (8,), (8,), (16, 8), (16, 8)]
Inputs values: ['not shown', array([5.8092922e-06, 5.8092922e-06]), 'not shown', 'not shown', 'not shown']
Outputs clients: [[_CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3), Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}(TensorConstant{(1,) of -0.5}, _CeleriteOp{name='factor_fwd', quiet=False}.0, TensorConstant{(1,) of 0.5}, Elemwise{Sqr}[(0, 0)].0), Elemwise{Composite{((-i0) / i1)}}(InplaceDimShuffle{0}.0, _CeleriteOp{name='factor_fwd', quiet=False}.0), Elemwise{TrueDiv}[(0, 0)](Elemwise{Sqr}[(0, 0)].0, _CeleriteOp{name='factor_fwd', quiet=False}.0), Elemwise{Log}[(0, 0)](_CeleriteOp{name='factor_fwd', quiet=False}.0)], [_CeleriteOp{name='solve_lower_fwd', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Join.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, TensorConstant{[[ 999.917..35199641]]}), _CeleriteOp{name='solve_lower_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Join.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, TensorConstant{[[ 999.917..35199641]]}, _CeleriteOp{name='solve_lower_fwd', quiet=False}.0, _CeleriteOp{name='solve_lower_fwd', quiet=False}.1, IncSubtensor{InplaceInc;::, int64}.0), _CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3)], [_CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-85507f45a7d6>", line 28, in <module>
    gp = GaussianProcess(kernel, t=x, yerr=sigma_lc)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/core.py", line 210, in __init__
    self.compute(t, **kwargs)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/core.py", line 316, in compute
    self._do_compute(quiet)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/celerite2.py", line 84, in _do_compute
    self._t, self._c, self._a, self._U, self._V
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/gof/op.py", line 642, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 85, in make_node
    for spec in self.spec["outputs"] + self.spec["extra_outputs"]
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 85, in <listcomp>
    for spec in self.spec["outputs"] + self.spec["extra_outputs"]

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
"""

The above exception was the direct cause of the following exception:

LinAlgError                               Traceback (most recent call last)
LinAlgError: failed to factorize or solve matrix
Apply node that caused the error: _CeleriteOp{name='factor_fwd', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]})
Toposort index: 34
Inputs types: [TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(17,), (2,), (17,), (17, 2), (17, 2)]
Inputs strides: [(8,), (8,), (8,), (16, 8), (16, 8)]
Inputs values: ['not shown', array([5.8092922e-06, 5.8092922e-06]), 'not shown', 'not shown', 'not shown']
Outputs clients: [[_CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3), Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}(TensorConstant{(1,) of -0.5}, _CeleriteOp{name='factor_fwd', quiet=False}.0, TensorConstant{(1,) of 0.5}, Elemwise{Sqr}[(0, 0)].0), Elemwise{Composite{((-i0) / i1)}}(InplaceDimShuffle{0}.0, _CeleriteOp{name='factor_fwd', quiet=False}.0), Elemwise{TrueDiv}[(0, 0)](Elemwise{Sqr}[(0, 0)].0, _CeleriteOp{name='factor_fwd', quiet=False}.0), Elemwise{Log}[(0, 0)](_CeleriteOp{name='factor_fwd', quiet=False}.0)], [_CeleriteOp{name='solve_lower_fwd', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Join.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, TensorConstant{[[ 999.917..35199641]]}), _CeleriteOp{name='solve_lower_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Join.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, TensorConstant{[[ 999.917..35199641]]}, _CeleriteOp{name='solve_lower_fwd', quiet=False}.0, _CeleriteOp{name='solve_lower_fwd', quiet=False}.1, IncSubtensor{InplaceInc;::, int64}.0), _CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3)], [_CeleriteOp{name='factor_rev', quiet=False}(TensorConstant{[-0.055775...05577527]}, Join.0, Alloc.0, Join.0, TensorConstant{[[ 9.99999..2674e-04]]}, _CeleriteOp{name='factor_fwd', quiet=False}.0, _CeleriteOp{name='factor_fwd', quiet=False}.1, _CeleriteOp{name='factor_fwd', quiet=False}.2, Elemwise{Composite{((i0 / i1) + ((i2 * i3) / sqr(i1)))}}.0, _CeleriteOp{name='solve_lower_rev', quiet=False}.3)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-85507f45a7d6>", line 28, in <module>
    gp = GaussianProcess(kernel, t=x, yerr=sigma_lc)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/core.py", line 210, in __init__
    self.compute(t, **kwargs)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/core.py", line 316, in compute
    self._do_compute(quiet)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/celerite2.py", line 84, in _do_compute
    self._t, self._c, self._a, self._U, self._V
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/theano/gof/op.py", line 642, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 85, in make_node
    for spec in self.spec["outputs"] + self.spec["extra_outputs"]
  File "/Users/eas342/anaconda/envs/py36/lib/python3.6/site-packages/celerite2/theano/ops.py", line 85, in <listcomp>
    for spec in self.spec["outputs"] + self.spec["extra_outputs"]

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-1-85507f45a7d6> in <module>
     36                       chains=2,
     37                       init="adapt_full",
---> 38                       target_accept=0.9)

~/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py in sample(draws, step, init, n_init, start, trace, chain_idx, chains, cores, tune, progressbar, model, random_seed, discard_tuned_samples, compute_convergence_checks, callback, jitter_max_retries, return_inferencedata, idata_kwargs, mp_ctx, pickle_backend, **kwargs)
    555         _print_step_hierarchy(step)
    556         try:
--> 557             trace = _mp_sample(**sample_args, **parallel_args)
    558         except pickle.PickleError:
    559             _log.warning("Could not pickle model, sampling singlethreaded.")

~/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/sampling.py in _mp_sample(draws, tune, step, chains, cores, chain, random_seed, start, progressbar, trace, model, callback, discard_tuned_samples, mp_ctx, pickle_backend, **kwargs)
   1474         try:
   1475             with sampler:
-> 1476                 for draw in sampler:
   1477                     trace = traces[draw.chain - chain]
   1478                     if trace.supports_sampler_stats and draw.stats is not None:

~/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/parallel_sampling.py in __iter__(self)
    478 
    479         while self._active:
--> 480             draw = ProcessAdapter.recv_draw(self._active)
    481             proc, is_last, draw, tuning, stats, warns = draw
    482             self._total_draws += 1

~/anaconda/envs/py36/lib/python3.6/site-packages/pymc3/parallel_sampling.py in recv_draw(processes, timeout)
    358             else:
    359                 error = RuntimeError("Chain %s failed." % proc.chain)
--> 360             raise error from old_error
    361         elif msg[0] == "writing_done":
    362             proc._readable = True

RuntimeError: Chain 0 failed.
```
</details>

**Comment by dfm** [comment]
This happens when the hyperparameters head into some pathological part of parameter space. You can use the `quiet` parameter to suppress the error, but this is generally indicative of some issue with the priors. Try playing with the priors to make them more restrictive and if you can't get it working, I can help debug.

**Comment by eas342** [comment]
Thanks for the quick response! Indeed `gp = GaussianProcess(kernel, t=x, yerr=sigma_lc,quiet=True)` suppresses the error and proceeds but doesn't address the root of the problem. You are right about the priors.

This sent me down the rabbit hole of understanding the log-normal distribution better. My prior was inspired by the example here (https://gallery.exoplanet.codes/en/latest/tutorials/quick-tess/), which sets
``` python
rho_gp = pm.Lognormal("rho_gp", mu=np.log(10.0), sigma=10.0)
```
This turns out to give the wildest PDF I have ever seen!! The mode of this distribution is 3.7e-43. The standard deviation is 2.7e44 (https://en.wikipedia.org/wiki/Log-normal_distribution). Perhaps the intention was to set `std=10.0` (ie. `sigma=0.694`)? That would give a mode of 6.1 and a standard deviation of 10 which won't involve such huge extremes. Should I file a github issue with `exoplanet`? It turns out one has to be careful with log normal distributions that have sigma>1.0 by more than a few.
![lognormal_pdf](https://user-images.githubusercontent.com/234377/105812721-eb5fde00-5f6b-11eb-80a3-55d1bb30ba11.png)
![lognormal_pdf_lin](https://user-images.githubusercontent.com/234377/105813698-74c3e000-5f6d-11eb-8682-963cb4a698d8.png)


I think this kind of situation could be avoided if there was an easy way to plot the prior function. I got quite confused by the abstract `theano` and `pymc3` stuff (I'm pretty new to them) and didn't see an obvious way to do it. The PDF plot was using `scipy.stats.lognorm`. Is there an easy way?

**Comment by dfm** [comment]
Hilarious! The `pm.Lognormal` distribution doesn't do what I thought it did! Yes - I'll update the tutorials to use something more reasonable.

For reference, here's how you can plot a PyMC3 distribution:

```python
x = np.linspace(-1, 10, 500)
y = pm.Lognormal.dist(mu=np.log(10), sigma=1.0).logp(np.exp(x)).eval()
plt.plot(x, np.exp(y))
```

**Comment by eas342** [comment]
Ah, thanks for the easy example of how to get the `logp` of the distribution!
